import { formatTimestamp } from './timeUtils.js';

/**
 * Convert caption objects to WebVTT format
 */
export function exportVTT(captions) {
  const sorted = [...(captions || [])].sort((a, b) => a.start - b.start);
  const lines = ['WEBVTT', '', 'NOTE Generated by CaptionAI', ''];

  sorted.forEach((cap, idx) => {
    const start = formatTimestamp(cap.start).replace(',', '.');
    const end   = formatTimestamp(cap.end).replace(',', '.');
    lines.push(String(idx + 1));
    lines.push(`${start} --> ${end} align:center`);
    if (cap.type === 'ac') {
      lines.push(`<c.ac-caption>${cap.text}</c>`);
    } else {
      lines.push(cap.text);
    }
    lines.push('');
  });

  return '\uFEFF' + lines.join('\r\n');
}

/**
 * Trigger browser file download
 */
export function downloadFile(content, filename, mimeType = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type: mimeType });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
